   #+BEGIN_COMMENT
   .. title: 昨年亡くなったNipsey hussleのドキュメンタリーの要約
   .. slug: TheMarathonContinues
   .. date: 2022-06-22 12:00:00 UTC-04:00
   .. tags: NipseyHussle
   .. link:
   .. description:
   .. type: text
   #+END_COMMENT
#+OPTIONS: tex:mathml

*  個人的なNipseyへの思い
こんばんは、今日は朝からNipsey hussleのドキュメンタリーを見てました。
Nipsey Hussleはアメリカの有名なヒップホップアーティストの一人で昨年２０１９年３月３１日に何者かに銃撃され亡くなってしまいました。
個人的にずっと応援していたので、彼の新しい音楽がもう聞けないのはとても悲しいことです。
他にも多くのアメリカの有名人が彼を追悼するメッセージを発信しており、彼の影響力が絶大だったことを改めて認識しました。
一方で、彼が歩んできた人生や彼の作品から得られた教訓や感情をもう一度思い出し、今後に活かすことも大事だなと思いました。
この記事ではNipseyのドキュメンタリーから得られた個人的な教訓を紹介していきます。

* ドキュメンタリーの感想
ちなみに今年の４月にこのドキュメンタリーがYoutubeで配信されたのですが、
全部で５話あるうちの１話あたりの視聴時間が３０分、そして英語字幕しかないため、かなり集中して視聴する必要がありました。
まず最初に感想になりますが、ドキュメンタリーを見てみると、私にとっては初めて知るNipseyの過去の出来事が大半であり、驚きました。
自分は日本でもかなりのNipseyファンだと勝手に思い込んでいて、正直誰よりもNipseyについては詳しいと思い込んでました。
このドキュメンタリーはすべて英語でしたが、Youtubeの字幕に助けられながらなんとか内容を理解しました。
これを見終わって思ったことは、Nipseyを大きくしたのは間違いなく彼の音楽に対する強い情熱であるということです。
そして彼の音楽に対する強い情熱が、周囲の人を巻き込み、彼をより高いステージへと引き上げたのだと感じました。

* Nipsey幼少期
このドキュメンタリーの始めでNipseyは、こう述べている。
”The marathon is about seeing long-term, seeing a vison, understand nothing really worthwhile happen overnight,
and just sticking to your script long enough to make something real happen.


Laying a brick every day instead of trying to build a brick wall,
just lay a brick eventually look up you have a brick wall.”

短くまとめるとMarathonとは「長期的な視点で物事を実現させるための過程」でしょうか。
恐らく彼の物事（プロジェクト）を実現させるためには相当な忍耐力が必要だっただろう。
